<Project Sdk="Microsoft.NET.Sdk.Worker">

  <ItemGroup>
    <ProjectReference Include="..\AIQuantTradingResearch.Application\AIQuantTradingResearch.Application.csproj" />
    <ProjectReference Include="..\AIQuantTradingResearch.Infrastructure\AIQuantTradingResearch.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
