using AIQuantTradingResearch.Application.MarketData;
using Xunit;

namespace AIQuantTradingResearch.Application.Tests;

public sealed class HistoricalMarketDataReadServiceTests
{
    private static readonly DateTimeOffset Now = new(2026, 9, 19, 12, 0, 0, TimeSpan.Zero);
    [Fact] public void KeyIncludesAllGovernedDimensions() { var key = Key(); Assert.NotEqual(key.Fingerprint, new HistoricalMarketDataCacheKey(CanonicalMarketSymbol.EthUsd, HistoricalCandleInterval.OneHour, HistoricalCandleRange.ThirtyDays, "Vike", HistoricalMarketDataReadService.CacheContractVersion).Fingerprint); Assert.NotEqual(key.Fingerprint, new HistoricalMarketDataCacheKey(CanonicalMarketSymbol.BtcUsd, HistoricalCandleInterval.FourHours, HistoricalCandleRange.ThirtyDays, "Vike", HistoricalMarketDataReadService.CacheContractVersion).Fingerprint); Assert.NotEqual(key.Fingerprint, new HistoricalMarketDataCacheKey(CanonicalMarketSymbol.BtcUsd, HistoricalCandleInterval.OneHour, HistoricalCandleRange.NinetyDays, "Vike", "v2").Fingerprint); }
    [Fact] public async Task FreshCacheHasZeroProviderCalls() { var cache = new Cache(Entry()); var provider = new Provider(Success()); var result = await Service(provider, cache).ReadAsync(Request()); Assert.Equal(HistoricalMarketDataReadState.Fresh, result.State); Assert.Equal(0, provider.Calls); }
    [Fact] public async Task MissingCacheAcquiresAndStores() { var cache = new Cache(); var provider = new Provider(Success()); var result = await Service(provider, cache).ReadAsync(Request()); Assert.Equal(HistoricalMarketDataReadState.Fresh, result.State); Assert.Equal(1, provider.Calls); Assert.NotNull(cache.Entry); }
    [Fact] public async Task ConcurrentIdenticalReadsUseOneGovernedAcquisition() { var completion = new TaskCompletionSource<HistoricalMarketDataResponse>(TaskCreationOptions.RunContinuationsAsynchronously); var provider = new Provider(completion.Task); var service = Service(provider, new Cache()); var reads = Enumerable.Range(0, 8).Select(_ => service.ReadAsync(Request())).ToArray(); await Task.Yield(); Assert.Equal(1, provider.Calls); completion.SetResult(Success()); var results = await Task.WhenAll(reads); Assert.All(results, r => Assert.Equal(HistoricalMarketDataReadState.Fresh, r.State)); Assert.Equal(1, provider.Calls); }
    [Fact] public async Task StaleRefreshFailureReturnsStale() { var provider = new Provider(HistoricalMarketDataResponse.Failed(HistoricalMarketDataFailure.RateLimited)); var result = await Service(provider, new Cache(Entry(Now.AddMinutes(-16)))).ReadAsync(Request()); Assert.Equal(HistoricalMarketDataReadState.Stale, result.State); Assert.Equal(HistoricalMarketDataFailure.RateLimited, result.Failure); }
    [Fact] public async Task FutureValidationTimestampIsNotFresh() { var provider = new Provider(Success()); var result = await Service(provider, new Cache(Entry(Now.AddMinutes(1)))).ReadAsync(Request()); Assert.Equal(1, provider.Calls); Assert.Equal(HistoricalMarketDataReadState.Fresh, result.State); }
    [Fact] public async Task MissingFailureIsControlledUnavailableAndEmptyIsSuccessful() { var unavailable = await Service(new Provider(HistoricalMarketDataResponse.Failed(HistoricalMarketDataFailure.Unavailable)), new Cache()).ReadAsync(Request()); var empty = await Service(new Provider(HistoricalMarketDataResponse.Available(Request(), [], Provenance())), new Cache()).ReadAsync(Request()); Assert.Equal(HistoricalMarketDataReadState.Unavailable, unavailable.State); Assert.Equal(HistoricalMarketDataReadState.Fresh, empty.State); Assert.Empty(empty.Candles!); }
    [Theory] [InlineData(HistoricalCandleInterval.OneHour, 15)] [InlineData(HistoricalCandleInterval.FourHours, 30)] [InlineData(HistoricalCandleInterval.OneDay, 120)] public void PolicyIsIntervalAware(HistoricalCandleInterval interval, int minutes) => Assert.Equal(TimeSpan.FromMinutes(minutes), HistoricalMarketDataReadService.GetFreshnessWindow(interval));
    private static HistoricalMarketDataReadService Service(Provider p, Cache c) => new(p, c, "Vike", new Clock()); private static HistoricalMarketDataRequest Request() => new(CanonicalMarketSymbol.BtcUsd, HistoricalCandleInterval.OneHour, HistoricalCandleRange.ThirtyDays, TimeSpan.FromSeconds(10)); private static HistoricalMarketDataCacheKey Key() => new(CanonicalMarketSymbol.BtcUsd, HistoricalCandleInterval.OneHour, HistoricalCandleRange.ThirtyDays, "Vike", HistoricalMarketDataReadService.CacheContractVersion); private static HistoricalMarketDataCacheEntry Entry(DateTimeOffset? validated = null) { var time = validated ?? Now.AddMinutes(-5); return new(Key(), Request(), [new HistoricalCandle(CanonicalMarketSymbol.BtcUsd, HistoricalCandleInterval.OneHour, Now.AddHours(-1), 10m, 12m, 9m, 11m, 100m)], new HistoricalMarketDataProvenance("Vike", time, time, false, true), Now); } private static HistoricalMarketDataProvenance Provenance() => new("Vike", Now, Now, false, true); private static HistoricalMarketDataResponse Success() => HistoricalMarketDataResponse.Available(Request(), Entry().Candles, Provenance()); private sealed class Clock : TimeProvider { public override DateTimeOffset GetUtcNow() => Now; }
    private sealed class Cache(HistoricalMarketDataCacheEntry? entry = null) : IHistoricalMarketDataCache { public HistoricalMarketDataCacheEntry? Entry { get; private set; } = entry; public Task<HistoricalMarketDataCacheLookup> RetrieveAsync(HistoricalMarketDataCacheKey key, CancellationToken ct = default) => Task.FromResult(Entry is null ? HistoricalMarketDataCacheLookup.Missing() : HistoricalMarketDataCacheLookup.Found(Entry)); public Task StoreAsync(HistoricalMarketDataCacheEntry entry, CancellationToken ct = default) { Entry = entry; return Task.CompletedTask; } }
    private sealed class Provider : IHistoricalMarketDataProvider { private readonly Task<HistoricalMarketDataResponse> response; public Provider(HistoricalMarketDataResponse response) : this(Task.FromResult(response)) { } public Provider(Task<HistoricalMarketDataResponse> response) => this.response = response; public int Calls { get; private set; } public Task<HistoricalMarketDataResponse> GetHistoricalCandlesAsync(HistoricalMarketDataRequest request, CancellationToken ct = default) { Calls++; return response; } }
}
