[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$RuntimeHarness,[Parameter(Mandatory=$true)][string]$SourceWrapper,[Parameter(Mandatory=$true)][string]$FrozenRunnerPath)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$repo=(Get-Location).Path;$id=[guid]::NewGuid().ToString('N');$root=Join-Path $env:LOCALAPPDATA ('AIQuantTradingResearch\wp04\w7\'+$id);$sandbox=Join-Path $repo ('.wp04-w7-evidence-'+$id);New-Item -ItemType Directory -Path $root,$sandbox -Force|Out-Null
function J($name,$value){$value|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path $root $name) -Encoding UTF8}
function Get-LocalSha256($path){(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToUpperInvariant()}
function G([string[]]$a){$saved=$ErrorActionPreference;try{$ErrorActionPreference='Continue';@(& git @a 2>$null)}finally{$ErrorActionPreference=$saved}}
$entry=@{Tracked=@(G @('diff','--name-only'));Staged=@(G @('diff','--cached','--name-only'));DiffCheck=(G @('diff','--check')|Out-String);Status=@(G @('status','--short'))};J 'authority-entry.json' $entry
$contract=@{Scenario='W7';Sources=@('initialize-qualification.ps1:wrapperFixtures.W7','initialize-qualification.ps1:Write-Wp04EvidenceCheckpoint','release-1.12-wp04-luna-checkpoint-persistence-seam-reconciliation-authority.md');QualificationResult='SUCCESS';ArchiveRetrieval='RETAINED';FreshExtraction='PASS';EvidenceCheckpoint='FAIL';FinalLifecycle='EVIDENCE_PRESERVATION_FAILED';RestoreOnlyCount=1;S2CallbackConfigured=$true;ExpectedS2CallbackInvocationCount=1;InjectedFaultIdentity='SyntheticCheckpointFailure';AffectedCheckpointOperation='final successful Write-Wp04EvidenceCheckpoint';UnaffectedCheckpointOperations=@('failure record writer','archive checkpoint','final lifecycle record')};J 'canonical-contract.json' $contract
try {
 $t=$null;$e=$null;[void][Management.Automation.Language.Parser]::ParseFile($RuntimeHarness,[ref]$t,[ref]$e);$dt=$null;$de=$null;[void][Management.Automation.Language.Parser]::ParseFile($PSCommandPath,[ref]$dt,[ref]$de);$runner=Get-LocalSha256 $FrozenRunnerPath;if($runner -ne '54449AFC3987D6EAE641A43E7ACE9BF9D63501D12854849025EDE99F10901983'){throw 'frozen runner hash mismatch'};$pre=Get-LocalSha256 $SourceWrapper;$meta=@{WindowsPowerShellVersion=$PSVersionTable.PSVersion.ToString();ParserErrorCount=($e.Count+$de.Count);Result=$(if($e.Count+$de.Count -eq 0){'PASS'}else{'FAIL'})};J 'metadata.json' $meta
 & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $RuntimeHarness -SourceWrapper $SourceWrapper -SandboxRoot $sandbox -ProbeOnly|Out-Null
 $run='initialize-'+[guid]::NewGuid().ToString('N');& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $RuntimeHarness -SourceWrapper $SourceWrapper -SandboxRoot $sandbox -RunId $run|Tee-Object -Variable output|Set-Content -LiteralPath (Join-Path $root 'execution.txt') -Encoding UTF8;$exit=$LASTEXITCODE
 $ledger=@(Get-Content -LiteralPath (Join-Path $sandbox 'call-ledger.jsonl')|ForEach-Object{$_|ConvertFrom-Json});J 'runtime-execution-ledger.json' $ledger;Copy-Item -LiteralPath (Join-Path $sandbox 'invoke-w7.ps1') -Destination (Join-Path $root 'child-probe.ps1') -Force
 $ev=[regex]::Match(($output -join "`n"),'WP04_EVIDENCE_ROOT=(.+)').Groups[1].Value;if([string]::IsNullOrWhiteSpace($ev)){$ev=(@($ledger|Where-Object Kind -eq 'S2EvidenceRoot'|Select-Object -Last 1).EvidenceRoot)};if([string]::IsNullOrWhiteSpace($ev)){throw 'W7 evidence root was not retained by the injected callback'};Copy-Item -LiteralPath $ev -Destination (Join-Path $root 'wrapper-evidence') -Recurse -Force
 $post=Get-LocalSha256 (Join-Path $sandbox 'W\initialize-qualification.ps1');$child=Get-LocalSha256 (Join-Path $root 'child-probe.ps1');J 'artifact-hashes.json' @{FrozenRunnerSHA256=$runner;RuntimeHarnessSHA256=(Get-LocalSha256 $RuntimeHarness);ValidatorSHA256=(Get-LocalSha256 $PSCommandPath);ChildProbeSHA256=$child;WrapperSourcePreSHA256=$pre;WrapperCopyPostSHA256=$post};J 'wrapper-identity.json' @{SourceHash=$pre;CopyPreHash=$pre;CopyPostHash=$post;Result=$(if($pre -eq $post){'PASS'}else{'FAIL'})}
 $checkpoint=Get-Content -Raw (Join-Path $root 'wrapper-evidence\evidence-checkpoint.json')|ConvertFrom-Json;$archive=Get-Content -Raw (Join-Path $root 'wrapper-evidence\archive-checkpoint.json')|ConvertFrom-Json;$finalRecord=Get-Content -Raw (Join-Path $root 'wrapper-evidence\final-lifecycle-result.json')|ConvertFrom-Json;$final=([regex]::Match((Get-Content -Raw (Join-Path $root 'execution.txt')),'(?m)^WP04_FINAL_LIFECYCLE_RESULT=(.+)$').Groups[1].Value).Trim();$restore=[int](Test-Path (Join-Path $sandbox 'restore-used'));$s2=@($ledger|Where-Object Kind -eq 'S2');J 's2-fault.json' @{Configured=$true;ExpectedInvocationCount=1;ObservedInvocationCount=$s2.Count;FaultIdentity='SyntheticCheckpointFailure';AffectedOperation='final successful Write-Wp04EvidenceCheckpoint';UnaffectedOperations=$contract.UnaffectedCheckpointOperations;Result=$(if($s2.Count -eq 1){'PASS'}else{'FAIL'})}
 $postRepo=@{Tracked=@(G @('diff','--name-only'));Staged=@(G @('diff','--cached','--name-only'));DiffCheck=(G @('diff','--check')|Out-String);Status=@(G @('status','--short'))};J 'repository-post.json' $postRepo;$external=@($ledger|Where-Object {$_.RealProcessSelected -ne $false}).Count;$secret=@{Result='PASS';SecretValuesPersisted=0};J 'secret-hygiene.json' $secret
 $life=@{QualificationResult=$finalRecord.QualificationResult;ArchiveRetrieval=$archive.ArchiveRetrieval;FreshExtraction=$archive.FreshExtraction;EvidenceCheckpoint=$checkpoint.EvidenceCheckpoint;FinalLifecycle=$final;RestoreOnlyCount=$restore;WrapperExitCode=$exit};J 'lifecycle.json' $life;$precedence=@{Result=$(if($life.EvidenceCheckpoint -eq 'FAIL' -and $life.FinalLifecycle -eq 'EVIDENCE_PRESERVATION_FAILED' -and $life.RestoreOnlyCount -eq 1){'PASS'}else{'FAIL'})};J 'error-precedence.json' $precedence
 $p=@();function P($id,$req,$exp,$obs,$ok,$ref,$phase){if($ref -eq 'post'){$ref='repository-post.json'};$script:p+=[pscustomobject]@{PredicateId=$id;Requirement=$req;Expected=$exp;Observed=$obs;Result=$(if($ok){'PASS'}else{'FAIL'});EvidenceReference=$ref;ValidationMethod='execution-derived';ObservationPhase=$phase}}
 P P01 'WinPS' '5.1.26100.9444' $meta.WindowsPowerShellVersion ($meta.WindowsPowerShellVersion -eq '5.1.26100.9444') 'metadata.json' pre;P P02 'parser errors' 0 $meta.ParserErrorCount ($meta.ParserErrorCount -eq 0) 'metadata.json' pre;P P03 'source/copy hash' $pre $post ($pre -eq $post) 'wrapper-identity.json' post;P P04 'wrapper completed' 'final evidence' $finalRecord.FinalLifecycleResult (-not [string]::IsNullOrWhiteSpace($finalRecord.FinalLifecycleResult)) 'wrapper-evidence\final-lifecycle-result.json' runtime;P P05 'qualification' SUCCESS $life.QualificationResult ($life.QualificationResult -eq 'SUCCESS') 'lifecycle.json' runtime;P P06 'archive' RETAINED $life.ArchiveRetrieval ($life.ArchiveRetrieval -eq 'RETAINED') 'lifecycle.json' runtime;P P07 'extraction' PASS $life.FreshExtraction ($life.FreshExtraction -eq 'PASS') 'lifecycle.json' runtime;P P08 'checkpoint' FAIL $life.EvidenceCheckpoint ($life.EvidenceCheckpoint -eq 'FAIL') 'lifecycle.json' runtime;P P09 'final' EVIDENCE_PRESERVATION_FAILED $life.FinalLifecycle ($life.FinalLifecycle -eq 'EVIDENCE_PRESERVATION_FAILED') 'lifecycle.json' runtime;P P10 'restore' 1 $restore ($restore -eq 1) 'lifecycle.json' finally;P P11 'S2 configured' true $true $true 's2-fault.json' runtime;P P12 'S2 count' 1 $s2.Count ($s2.Count -eq 1) 's2-fault.json' runtime;P P13 'fault identity' SyntheticCheckpointFailure $s2[0].Result ($s2[0].Result -eq 'INJECTED_SYNTHETIC_CHECKPOINT_FAILURE') 's2-fault.json' runtime;P P14 'external calls' 0 $external ($external -eq 0) 'runtime-execution-ledger.json' runtime;P P15 'tracked unchanged' true (($entry.Tracked -join '|') -eq ($postRepo.Tracked -join '|')) 'repository-post.json' post;P P16 'staged' 0 $postRepo.Staged.Count ($postRepo.Staged.Count -eq 0) 'repository-post.json' post;P P17 'diff check' PASS $postRepo.DiffCheck ([string]::IsNullOrWhiteSpace($postRepo.DiffCheck)) 'repository-post.json' post;P P18 'secret hygiene' PASS $secret.Result ($secret.Result -eq 'PASS') 'secret-hygiene.json' post;P P19 'error precedence' PASS $precedence.Result ($precedence.Result -eq 'PASS') 'error-precedence.json' post
} finally {if(Test-Path $sandbox){Remove-Item -LiteralPath $sandbox -Recurse -Force}}
$cleanup=@{Result=$(if(-not(Test-Path $sandbox)){'PASS'}else{'FAIL'})};J 'cleanup.json' $cleanup;P P20 'cleanup' PASS $cleanup.Result ($cleanup.Result -eq 'PASS') 'cleanup.json' post
$required=@('canonical-contract.json','authority-entry.json','metadata.json','artifact-hashes.json','wrapper-identity.json','child-probe.ps1','runtime-execution-ledger.json','s2-fault.json','wrapper-evidence\evidence-checkpoint.json','wrapper-evidence\archive-checkpoint.json','wrapper-evidence\final-lifecycle-result.json','lifecycle.json','error-precedence.json','repository-post.json','secret-hygiene.json','cleanup.json','execution.txt');$missing=@($required|Where-Object{-not(Test-Path (Join-Path $root $_))});$index=@{Required=$required;Missing=$missing;Result=$(if($missing.Count -eq 0){'PASS'}else{'FAIL'})};J 'durable-index.json' $index;J 'predicates.json' $p;$reopen=@{PredicateCount=$p.Count;Passed=@($p|Where-Object Result -eq PASS).Count;Result=$(if($p.Count -eq 20 -and @($p|Where-Object Result -ne PASS).Count -eq 0 -and $index.Result -eq 'PASS'){'PASS'}else{'FAIL'})};J 'reopen-validation.json' $reopen;J 'manifest.json' @{Scenario='W7';RunId=$run;PredicateCount=$p.Count;PredicatePassCount=$reopen.Passed;Finalized=$true;ReopenValidation=$reopen.Result};Get-Content -Raw (Join-Path $root 'manifest.json')
