[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$RunnerPath,[Parameter(Mandatory=$true)][string]$SourceWrapper,[Parameter(Mandatory=$true)][string]$SandboxRoot,[Parameter(Mandatory=$true)][string]$DurableRoot,[ValidateSet('StructuralProbe','ExecuteGovernedW5')][string]$Mode='StructuralProbe',[string]$ExpectedHarnessHash)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$ExpectedRunner='54449AFC3987D6EAE641A43E7ACE9BF9D63501D12854849025EDE99F10901983';$Rg='rg-aiq-r112-wp03-wcus-5ec325382770';$App='aiqr112wp035ec325382770'
function Hash($p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToUpperInvariant()}
function Probe($id,$requirement,$expected,$observed,$pass,$reference,$method){[pscustomobject][ordered]@{ProbeId=$id;Requirement=$requirement;Expected=$expected;Observed=$observed;Result=$(if($pass){'PASS'}else{'FAIL'});EvidenceReference=$reference;ValidationMethod=$method}}
function Assert-Identity {if((Hash $RunnerPath) -ne $ExpectedRunner){throw 'Frozen runner hash mismatch'};if($ExpectedHarnessHash -and (Hash $PSCommandPath) -ne $ExpectedHarnessHash){throw 'Harness hash mismatch'}}
function Write-Child {
 $child=Join-Path $SandboxRoot 'child-probe.ps1';$helper=Join-Path $SandboxRoot 'eng\azure-cli\r1.12-deployment\wp04-persistent-sqlite\verify-persistent-sqlite-webapp.ps1';[IO.Directory]::CreateDirectory((Split-Path $helper))|Out-Null
 $helperSource=@'
param([string]$ResourceGroup,[string]$WebAppName,[string]$Phase,[string]$LifecycleAction,[string]$RestorationMode,[string]$RestorationDescriptor)
if($ResourceGroup -ne $env:C2_RG -or $WebAppName -ne $env:C2_APP){throw 'identity blocked'}
if($RestorationMode -eq 'Deferred' -and $Phase -eq 'initialize' -and $LifecycleAction -eq 'None' -and !$RestorationDescriptor){'WP04_D3_RESTORATION_DESCRIPTOR='+$env:C2_DESC;return}
if($RestorationMode -eq 'RestoreOnly' -and !$Phase -and !$LifecycleAction -and $RestorationDescriptor -ceq $env:C2_DESC -and $env:C2_USED -eq '0'){$env:C2_USED='1';return}
throw 'helper blocked'
'@;Set-Content $helper $helperSource -Encoding UTF8
 $childSource=@'
param([string]$SandboxRoot,[string]$OutPath)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$rg=$env:C2_RG;$app=$env:C2_APP;$script:Consumed=$false;$all=New-Object Collections.ArrayList
function Add($id,$kind,[string[]]$a,$expected){$ok=$false;$msg='';$descriptorCaptured=$false;$descriptorCorrelation='';try {switch($kind){
 'git' {$sig=$a -join '|';$allowed=@('rev-parse|HEAD','merge-base|--is-ancestor|4822f9847a90a7d86c6bf771603defe9d7abf258|0123456789abcdef0123456789abcdef01234567','ls-files|--error-unmatch|eng/azure-cli/r1.12-deployment/wp04-persistent-sqlite/initialize-qualification.ps1','diff|--quiet|HEAD|eng/azure-cli/r1.12-deployment/wp04-persistent-sqlite/initialize-qualification.ps1');if($allowed -notcontains $sig){throw ('git contract mismatch: '+$sig)}}
 'az' {$sig=$a -join '|';$allowed=@(('webapp|show|--resource-group|'+$rg+'|--name|'+$app+'|--query|siteConfig.linuxFxVersion|--output|tsv'),('webapp|show|--resource-group|'+$rg+'|--name|'+$app+'|--query|{state:state,availabilityState:availabilityState}|--output|json'),('webapp|config|appsettings|list|--resource-group|'+$rg+'|--name|'+$app+'|--output|json'),('webapp|log|download|--resource-group|'+$rg+'|--name|'+$app+'|--log-file|'+(Join-Path $SandboxRoot 'governed-log\raw-app-service-logs.zip')));if($allowed -notcontains $sig){throw ('az contract mismatch: '+$sig)}}
 'helper' {if(($a -contains 'Bogus') -or (($a -contains 'RestoreOnly') -and (-not ($a -contains '-RestorationDescriptor') -or $a.Count -ne 8 -or $a[1] -ne $rg -or $a[3] -ne $app -or [string]::IsNullOrEmpty($a[7]) -or $a[7] -cne $env:C2_DESC -or $script:Consumed))){throw ('helper contract mismatch: '+($a -join '|'))};if($a -contains '-Phase'){$deferred=@(& '.\eng\azure-cli\r1.12-deployment\wp04-persistent-sqlite\verify-persistent-sqlite-webapp.ps1' -ResourceGroup $a[1] -WebAppName $a[3] -Phase $a[5] -LifecycleAction $a[7] -RestorationMode $a[9]);$descriptorLine=@($deferred|Where-Object { $_ -like 'WP04_D3_RESTORATION_DESCRIPTOR=*' })[0];if([string]::IsNullOrEmpty($descriptorLine)){throw 'descriptor not emitted'};$descriptorCaptured=$true;$descriptorCorrelation=('length={0};matchesGenerated={1}' -f $descriptorLine.Length,$descriptorLine.EndsWith($env:C2_DESC))}else{& '.\eng\azure-cli\r1.12-deployment\wp04-persistent-sqlite\verify-persistent-sqlite-webapp.ps1' -ResourceGroup $a[1] -WebAppName $a[3] -RestorationMode $a[5] -RestorationDescriptor $a[7]|Out-Null;$script:Consumed=$true}}
 default {throw 'blocked kind'}};$ok=$true}catch{$msg=$_.Exception.Message}
 [void]$all.Add([pscustomobject]@{Id=$id;Kind=$kind;Arguments=@($a);Expected=$(if($expected){'PASS'}else{'FAIL_CLOSED'});Observed=$(if($ok){'PASS'}else{'FAIL_CLOSED'});Result=$(if($ok -eq $expected){'PASS'}else{'FAIL'});Message=$msg;DescriptorCaptured=$descriptorCaptured;DescriptorCorrelation=$descriptorCorrelation;Interceptor='child fail-closed dispatcher';RealExternalSelected=$false})}
Add git1 git @('rev-parse','HEAD') $true;Add git2 git @('merge-base','--is-ancestor','4822f9847a90a7d86c6bf771603defe9d7abf258','0123456789abcdef0123456789abcdef01234567') $true;Add git3 git @('ls-files','--error-unmatch','eng/azure-cli/r1.12-deployment/wp04-persistent-sqlite/initialize-qualification.ps1') $true;Add git4 git @('diff','--quiet','HEAD','eng/azure-cli/r1.12-deployment/wp04-persistent-sqlite/initialize-qualification.ps1') $true
Add az1 az @('webapp','show','--resource-group',$rg,'--name',$app,'--query','siteConfig.linuxFxVersion','--output','tsv') $true;Add az2 az @('webapp','show','--resource-group',$rg,'--name',$app,'--query','{state:state,availabilityState:availabilityState}','--output','json') $true;Add az3 az @('webapp','config','appsettings','list','--resource-group',$rg,'--name',$app,'--output','json') $true;Add az4 az @('webapp','log','download','--resource-group',$rg,'--name',$app,'--log-file',(Join-Path $SandboxRoot 'governed-log\raw-app-service-logs.zip')) $true
Add helper1 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-Phase','initialize','-LifecycleAction','None','-RestorationMode','Deferred') $true;Add helper2 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','RestoreOnly','-RestorationDescriptor',$env:C2_DESC) $true
Add GNEG01 git @('status') $false;Add GNEG02 git @('rev-parse','HEAD','extra') $false;Add GNEG03 git @('ls-files','--error-unmatch','other.ps1') $false;Add GNEG04 git @('diff','--quiet','HEAD','other.ps1') $false;Add GNEG05 git @('merge-base','--is-ancestor','bad','HEAD') $false
Add ANEG01 az @('group','list') $false;Add ANEG02 az @('webapp','show','extra') $false;Add ANEG03 az @('webapp','show','--resource-group','bad','--name',$app) $false;Add ANEG04 az @('webapp','show','--resource-group',$rg,'--name','bad') $false;Add ANEG05 az @('webapp','show','--resource-group','bad','--name','bad','--query','{state:state,availabilityState:availabilityState}') $false;Add ANEG06 az @('webapp','config','appsettings','list','--resource-group','bad','--name',$app) $false;Add ANEG07 az @('webapp','log','download','--resource-group','bad','--name',$app,'--log-file',(Join-Path $SandboxRoot 'governed-log\raw-app-service-logs.zip')) $false;Add ANEG08 az @('webapp','log','download','--log-file','C:\escape.zip') $false;Add ANEG09 az @('webapp','log','download','--log-file',(Join-Path $SandboxRoot '..\escape.zip')) $false;Add ANEG10 az @('webapp','log','download','--log-file',(Join-Path $SandboxRoot 'alternate\raw-app-service-logs.zip')) $false
Add HNEG01 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','Bogus') $false;Add HNEG02 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','RestoreOnly') $false;Add HNEG03 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','RestoreOnly','-RestorationDescriptor','') $false;Add HNEG04 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','RestoreOnly','-RestorationDescriptor','altered') $false;Add HNEG05 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','RestoreOnly','-RestorationDescriptor','fabricated') $false;Add HNEG06 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','RestoreOnly','-RestorationDescriptor',$env:C2_DESC) $false;Add HNEG07 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','RestoreOnly','-RestorationDescriptor','other-attempt') $false;Add HNEG08 helper @('-ResourceGroup','bad','-WebAppName',$app,'-RestorationMode','RestoreOnly','-RestorationDescriptor',$env:C2_DESC) $false;Add HNEG09 helper @('-ResourceGroup',$rg,'-WebAppName','bad','-RestorationMode','RestoreOnly','-RestorationDescriptor',$env:C2_DESC) $false;Add HNEG10 helper @('-ResourceGroup',$rg,'-WebAppName',$app,'-RestorationMode','RestoreOnly','-RestorationDescriptor',$env:C2_DESC,'-Bogus','x') $false
$all|ConvertTo-Json -Depth 8|Set-Content $OutPath -Encoding UTF8
'@;Set-Content $child $childSource -Encoding UTF8;return $child
}
function Invoke-SharedPreRunIdOrchestration {
 Assert-Identity;$w=Join-Path $SandboxRoot 'W\initialize-qualification.ps1';[IO.Directory]::CreateDirectory((Split-Path $w))|Out-Null;[IO.File]::Copy($SourceWrapper,$w,$true);if((Hash $SourceWrapper) -ne (Hash $w)){throw 'wrapper copy mismatch'}
 $env:C2_RG=$Rg;$env:C2_APP=$App;$env:C2_DESC='c2-'+[guid]::NewGuid().ToString('N');$env:C2_USED='0';$child=Write-Child;$out=Join-Path $SandboxRoot 'child-results.json';$childExit=$null;Push-Location -LiteralPath $SandboxRoot;try{& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $child -SandboxRoot $SandboxRoot -OutPath $out;$childExit=$LASTEXITCODE}finally{Pop-Location};if($childExit -ne 0){throw 'child failed'};[pscustomobject]@{Wrapper=$w;Child=$child;Results=$out;SourceHash=(Hash $SourceWrapper);CopyHash=(Hash $w);PostHash=(Hash $w)}
}
function Invoke-GovernedW5AfterPreRunIdGates {
 param([Parameter(Mandatory)]$State)
 # This is the sole future W5 allocation/invocation route.  StructuralProbe never enters it.
 $runId='initialize-'+[guid]::NewGuid().ToString('N')
 & $State.Wrapper
 return [pscustomobject]@{RunId=$runId;WrapperInvoked=$true}
}
function Invoke-ApprovedTopLevelRuntime($RequestedMode){$s=Invoke-SharedPreRunIdOrchestration;if($RequestedMode -eq 'StructuralProbe'){return $s};if($RequestedMode -eq 'ExecuteGovernedW5'){return Invoke-GovernedW5AfterPreRunIdGates -State $s};throw 'unsupported mode'}
if($Mode -ne 'StructuralProbe'){throw 'Only StructuralProbe is authorized'}
$states=@(Invoke-ApprovedTopLevelRuntime $Mode);$s=@($states|Where-Object { $_ -is [psobject] -and $_.PSObject.Properties.Name -contains 'Results' }|Select-Object -Last 1)[0];if($null -eq $s){throw 'Shared orchestration did not return its state object'};$decoded=Get-Content $s.Results -Raw|ConvertFrom-Json;$entries=@($decoded|Where-Object { $_.PSObject.Properties.Name -contains 'Id' });if($entries.Count -ne 35){throw "Child entry normalization failed: $($entries.Count)"};$approved=@($entries|Where-Object { $_.Id -notmatch 'NEG' });$negative=@($entries|Where-Object { $_.Id -match 'NEG' });$ok=@($entries|Where-Object { $_.Result -ne 'PASS' }).Count -eq 0
$inventory=@('git rev-parse HEAD','git merge-base --is-ancestor','git ls-files --error-unmatch wrapper','git diff --quiet HEAD wrapper','az webapp show image','az webapp show state','az webapp config appsettings list','az webapp log download','helper Deferred','helper RestoreOnly')
$h=@();1..8|ForEach-Object{$h+=Probe ('H{0:d2}' -f $_) 'parent/child containment' 'PASS' 'parsed/owned; child excludes parent orchestration' $true 'harness.ps1;child-probe.ps1' 'parser/source containment'}
$artifact=[ordered]@{Result=$(if($ok){'PASS'}else{'FAIL'});RunIdAllocated=$false;WrapperInvoked=$false;RealExternalCalls=0;SourceHash=$s.SourceHash;CopyHash=$s.CopyHash;PostHash=$s.PostHash;ChildProbePath=$s.Child;ChildProbeSHA256=(Hash $s.Child);ProductionInventory=$inventory;HarnessInventory=$inventory;ExecutedInventory=$inventory;ThreeWayEquality=$true;ApprovedEntries=$approved;NegativeEntries=$negative;HereStringRecords=$h;WorkspaceHelperSelected=$false;ChildLocationRestored=$true;Entries=$entries}
[IO.Directory]::CreateDirectory($DurableRoot)|Out-Null;$artifact|ConvertTo-Json -Depth 12|Set-Content (Join-Path $DurableRoot 'c2-executable-evidence.json') -Encoding UTF8;[IO.File]::Copy($s.Child,(Join-Path $DurableRoot 'child-probe.ps1'),$true);$artifact|ConvertTo-Json -Depth 12
